import { type SiteConfig } from './siteConfig';

export const LOCAL_SITE_CONFIG: SiteConfig = {
  introText: "Looking for a digital product\nthat understands your users\nand helps your business grow?",
  introScrollPrompt: "Scroll to explore the work",
  introOverlayBackdropColor: "rgba(0, 0, 0, 0.6)",
  introOverlayBackdropOpacity: 0.35,
  reducedMotion: false,
  featured: {
    titleLine1: "",
    titleLine2: "Featured Work",
    testimonialsTitle: "What people say",
    description: "I turn user understanding into intelligent digital products — combining UX research, cinematic interface design, AI-powered workflows, and business-focused product thinking to help founders build products people actually use and businesses can grow from.",
    testimonialsEyebrow: "",
    caseStudyLabel: "Case Study",
    liveLabel: "Live App",
    viewAllLabel: "View All Projects",
    heroSecondaryLabel: "View My Work",
    ctaTitleLine1: "Take your product",
    ctaTitleLine2: "to the next level",
    ctaDescription: "Gain complete visibility over your digital experience. Let's design intuitive, engaging, and high-performing interfaces that drive real business outcomes.",
    ctaButtonText: "Start a project",
    ctaButtonHref: "https://www.oussamalassoued.me/contact",
  },
  projects: [],
  testimonials: [],
  videos: [],
  articles: [],
  scene05: {
    heroTitleLine1: "",
    heroTitleLine2: "",
    heroSubtitle: "",
    portraitCaption: "",
    skills: [],
    companyLogos: [],
    certifications: [],
    featuredCertifications: [],
    valueCards: [],
    companyLogosTitle: "",
    valuesEyebrow: "",
    visionTitle: "",
    visionText: "",
    skillsEyebrow: "",
    skillsTitle: "",
    certificationsTitle: "",
    featured: [],
    actionHref: "#",
  },
  contactPage: {
    heroTitleLine1: "",
    heroTitleLine2: "Let's Work Together",
    heroSubtitle: "Open for projects, collaborations, and conversations focused on creating clear, human-centered digital experiences.",
    directContactTitle: "Direct Contact",
    phoneLabel: "Phone",
    phoneNumber: "+216 93 126 283",
    emailLabel: "Email",
    emailAddress: "work.oussama.lassoued@gmail.com",
    officeLabel: "Location",
    officeAddress: "La Manouba, Tunisia",
    availabilityText: "Available for projects worldwide",
    responseTimeLabel: "Response Time",
    responseTimeValue: "< 24 hours",
    responseTimeDescription: "I typically respond within one business day",
    formTitle: "Send a Message",
    formSubtitle: "I'd love to hear from you. Fill out the form below and I'll get back to you as soon as possible.",
    formNameLabel: "Your Name",
    formNamePlaceholder: "Oussama Lassoued",
    formEmailLabel: "Email Address",
    formEmailPlaceholder: "work.oussama.lassoued@gmail.com",
    formSubjectLabel: "Subject",
    formSubjectPlaceholder: "Project, collaboration, idea...",
    formMessageLabel: "Message",
    formMessagePlaceholder: "What are you trying to build? What problem are you facing? The more context you share, the better I can help.",
    formPrivacyText: "By submitting, you agree to our",
    formPrivacyLink: "#/privacy-policy",
    formSubmitButton: "Send Message",
    socialSectionLabel: "Social Channels",
    socialSectionTitle: "Connect on Social",
    socialSectionDescription: "",
    contactCards: [],
    formSuccessTitle: "Message Sent!",
    formSuccessMessage: "Thank you for reaching out. I've received your message and will get back to you within 24 hours.",
    validationRequired: "This field is required",
    validationInvalidEmail: "Please enter a valid email address",
    validationMinLength: "Message must be at least 10 characters",
    honeypotFieldName: "website_url",
    maxMessageLength: 5000,
    minMessageLength: 10,
    rateLimitMinutes: 5,
  },
  dashboard: {
    browser: {
      browserTabTitle: "Oussama Lassoued | UX/UI Designer",
      faviconUrl: "",
    },
    "integrations": {
      "apiBaseUrl": "https://api.example.com",
      "customDomain": "portfolio.example.com",
      "googleAnalyticsMeasurementId": "G-PGKYQ61JPJ",
      "googleAnalyticsEnabled": false,
    },
  },
  footer: {
    brandTitle: "Oussama Lassoued",
    brandDescription: "UX/UI Designer and AI Product Builder",
    email: "work.oussama.lassoued@gmail.com",
    quickLinksTitle: "Quick Links",
    followTitle: "Follow",
    ctaTitle: "Get in touch",
    ctaDescription: "Let's build something together.",
    ctaButtonLabel: "Start a project",
    ctaButtonHref: "#home",
    copyrightText: "Oussama Lassoued",
    bottomNote: "",
    socialLinks: [],
    legalLinks: [],
    navLinks: [],
  },
  visibility: {
    footerEmail: true,
    footerNavLinks: true,
    footerSocialLinks: true,
    letsTalkButton: true,
    footerLegalLinks: true,
    staticHomeLayout: true,
  },
  designSystem: {
    components: {
      featuredCtaButtonVariant: 'button-1',
      featuredViewAllButtonVariant: 'button-2',
    },
    foundation: {
      spacing: { sectionPaddingRem: 4, stackGapRem: 1, gridGapRem: 1, cardPaddingRem: 1, layout: { contentMaxWidthPx: 1200, columnGapRem: 2, maxGridColumns: 12 } },
      typography: { eyebrowSizeRem: 0.75, eyebrowLetterSpacingEm: 0.08, eyebrowWeight: 600 },
    },
    theme: {
      primaryColor: '#030213',
      secondaryColor: '#ececf0',
      onPrimaryColor: '#ffffff',
      onSecondaryColor: '#030213',
      displayTitleSizeRem: 4.4,
      sectionTitleSizeRem: 2.25,
      bodyTextSizeRem: 1,
      headingScale: 1.2,
      headingWeight: 600,
      headingLetterSpacingEm: -0.02,
      bodyLineHeight: 1.4,
      buttonRadius: 24,
      buttonBorderWidth: 1,
      buttonShadowOpacity: 0.16,
      cardRadius: 16,
      cardBorderWidth: 1,
      cardBlurPx: 8,
      cardShadowOpacity: 0.12,
      glassTintColor: 'rgba(255,255,255,0.6)',
      glassBorderColor: 'rgba(0,0,0,0.04)',
      glowColor: '#ffdcae',
      glowEnabled: false,
      glowIntensity: 0.2,
    },
    componentsDefaults: {},
  },
  analytics: {},
  inbox: {},
};

export default LOCAL_SITE_CONFIG;
